
--ADD CONSTRAINT

ALTER TABLE CLIENT 
ADD CONSTRAINT MyUniqueConstraint UNIQUE(CLIENTID);

ALTER TABLE CLIENT
ADD CONSTRAINT mycheckconstraint CHECK(purpose > 0)


--DISABLE CONSTRAINT
ALTER TABLE CLIENT NOCHECK CONSTRAINT mycheckconstraint

--ENABLE CONSTRAINT
ALTER TABLE CLIENT  CHECK CONSTRAINT mycheckconstraint

--DELETE CONSTRAINT
ALTER TABLE CLIENT DROP CONSTRAINT mycheckconstraint;